name: Build
on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Algolia Docsearch Uploader
        uses: guzhongren/algolia-docsearch-upload-action@v2.0.0
        env:
          FILE_PATH: "../../assets/algolia.json"
          APPLICATION_ID: "U78G8QR4DU"
          ADMIN_API_KEY: "6210ead870813aadae2d72f3681e8bb9"
          INDEX_NAME: "ziyuesinicization"

